name: Auto-approve and merge bot PRs

on:
  pull_request_target:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-and-merge:
    if: github.actor == 'github-actions[bot]' || github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
