name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 2"

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Install Cosign
        id: install-cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.8.2
        with:
          cosign-release: 'v2.4.2'

      - name: Set Build Tag
        id: set-env
        run: |
          echo "TAG=$(date +%Y.%m.%d)" >> $GITHUB_ENV
          echo "TAG is set to $(date +%Y.%m.%d)"

      - name: Docker Login
        id: docker-login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        id: github-login
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        id: setup-qemu
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        id: buildx-setup
        uses: docker/setup-buildx-action@v3.10.0

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: | 
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            latest
            ${{ env.TAG }}

      - name: Docker Bake Build and Push
        uses: docker/bake-action@v4
        with:
          files: ./docker-bake.hcl
          targets: main
          push: true
          sbom: true
          provenance: mode=max
          set: |
            main.tags=${{ steps.meta.outputs.tags }}
            main.labels=${{ steps.meta.outputs.labels }}

      - name: Slim Docker Image for amd64
        id: slim-amd64
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_NEW_LABEL: ${{ steps.meta.outputs.labels }}
          DSLIM_IMAGE_BUILD_ARCH: amd64
          DSLIM_HTTP_PROBE: false
        with:
          target: ${{ github.repository }}:latest
          tag: slim-amd64

      - name: Slim Docker Image for arm64
        id: slim-arm64
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_NEW_LABEL: ${{ steps.meta.outputs.labels }}
          DSLIM_IMAGE_BUILD_ARCH: arm64
          DSLIM_HTTP_PROBE: false
        with:
          target: ${{ github.repository }}:latest
          tag: slim-arm64

      - name: Push Intermediate Slim Images
        run: |
          docker tag ${{ github.repository }}:slim-amd64 ghcr.io/${{ github.repository }}:slim-amd64
          docker tag ${{ github.repository }}:slim-arm64 ghcr.io/${{ github.repository }}:slim-arm64
          docker push ${{ github.repository }}:slim-amd64
          docker push ${{ github.repository }}:slim-arm64
          docker push ghcr.io/${{ github.repository }}:slim-amd64
          docker push ghcr.io/${{ github.repository }}:slim-arm64

      - name: Create and Push Multi-Arch Manifest for Slim Image
        uses: Noelware/docker-manifest-action@1.0.0
        with:
          inputs: ${{ github.repository }}:slim
          tags: ${{ github.repository }}:slim-amd64,${{ github.repository }}:slim-arm64
          push: true

      - name: Create and Push Multi-Arch Manifest for Slim Image for GHCR
        uses: Noelware/docker-manifest-action@1.0.0
        with:
          inputs: ghcr.io/${{ github.repository }}:slim
          tags: ghcr.io/${{ github.repository }}:slim-amd64,ghcr.io/${{ github.repository }}:slim-arm64
          push: true

      - name: Generate artifact attestation
        id: artifacts
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for GHCR
        id: artifacts-ghcr
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Generate SBOM GHCR
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}:latest
          format: 'spdx-json'
          output-file: 'sbom.spdx.json'

      - name: Attest SBOM GHCR
        uses: actions/attest-sbom@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          sbom-path: 'sbom.spdx.json'
          push-to-registry: true

      - name: Sign the Published Docker Image
        id: sign-image
        if: github.event_name != 'pull_request'
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build.outputs.digest }}
        run: |
          for tag in $TAGS; do
            echo "Signing ${tag}@${DIGEST}"
            COSIGN_EXPERIMENTAL=1 cosign sign --yes "${tag}@${DIGEST}"
          done

      - name: Sign Slim Image
        id: sign-slim
        if: github.event_name != 'pull_request'
        env:
          COSIGN_EXPERIMENTAL: 1
          SLIM_TAGS: "${{ github.repository }}:slim ghcr.io/${{ github.repository }}:slim"
        run: |
          for tag in $SLIM_TAGS; do
            cosign sign --yes "${tag}"
          done

      - name: Generate Release Notes (Docker & Supply Chain Info)
        if: github.event_name == 'release'
        run: |
          TAG="${{ env.TAG }}"
          REPO="${{ github.repository }}"
          cat <<EOF > release_notes.txt
## 🚀 Docker Images for This Release

This release provides multi-architecture Docker images (\`amd64\`, \`arm64\`, and \`arm\`) published to both **Docker Hub** and **GitHub Container Registry (GHCR)**.

---

### 🔹 **Docker Hub**

> **Note:** Docker Hub is the world's most popular public container registry, but it enforces [anonymous pull limits](https://www.docker.com/increase-rate-limits). If you are automating deployments or have many servers, consider using GHCR below to avoid interruptions.

**Repository:** \`${REPO}\`  
**Tags available:** \`latest\`, \`${TAG}\`

**Pull commands:**
\`\`\`sh
docker pull ${REPO}:latest
docker pull ${REPO}:${TAG}
\`\`\`

---

### 🔹 **GitHub Container Registry (GHCR)**

> **GHCR** offers higher pull rate limits, strong integration with GitHub, and is recommended for most CI/CD or cloud-native environments.

**Repository:** \`ghcr.io/${REPO}\`  
**Tags available:** \`latest\`, \`${TAG}\`

**Pull commands:**
\`\`\`sh
docker pull ghcr.io/${REPO}:latest
docker pull ghcr.io/${REPO}:${TAG}
\`\`\`

---

### 🔒 Supply Chain Security

These images are signed and include:

- **SLSA Provenance:** Attestations to verify how the image was built.
- **SBOM:** Software Bill of Materials for full component transparency.
- **Cosign signatures** for tamper-evidence and trust.

**How to verify:**
\`\`\`sh
# Verify image signature
cosign verify ghcr.io/${REPO}:${TAG}

# Verify SLSA provenance
cosign verify-attestation ghcr.io/${REPO}:${TAG}

# List SBOM attestations
cosign verify-attestation --type sbom ghcr.io/${REPO}:${TAG}
\`\`\`
See [Sigstore Cosign Docs](https://docs.sigstore.dev/cosign/overview/) for full instructions.

---

#### Need help or want to report an issue?  
Open an issue on [GitHub](https://github.com/${REPO}/issues).
EOF

      - name: Create Github release
        id: github-releasing
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{ env.TAG }}
          allowUpdates: true
          makeLatest: true
          bodyFile: release_notes.txt
