name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 2"

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Cosign
        id: install-cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.8.0
        with:
          cosign-release: 'v2.4.2'

      - name: Set Build Tag
        id: set-env
        run: |
          echo "TAG=$(date +%Y.%m.%d)" >> $GITHUB_ENV
          echo "TAG is set to $(date +%Y.%m.%d)"

      - name: Docker Login
        id: docker-login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        id: setup-qemu
        uses: docker/setup-qemu-action@v3.4.0

      - name: Set up Docker Buildx
        id: buildx-setup
        uses: docker/setup-buildx-action@v3.9.0

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            latest
            ${{ env.TAG }}

      - name: Build and Push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          sbom: true
          provenance: mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Generate artifact attestation
        id: artifacts
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Sign the Published Docker Image
        id: sign-image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build.outputs.digest }}
        run: |
          for tag in $TAGS; do
            echo "Signing ${tag}@${DIGEST}"
            COSIGN_EXPERIMENTAL=1 cosign sign --yes "${tag}@${DIGEST}"
          done

      - name: Create github release
        id: github-releasing
        uses: ncipollo/release-action@v1.15.0
        with:
          tag: ${{ env.TAG }}
          allowUpdates: true
          makeLatest: true

